### ISSUE TITLE
We can't remove public methods on non-internal types without a deprecation cycle

### ISSUE THREAD

**Issue by Shoaib050041** [Shoaib050041/sweatcoin#1]
We can't remove public methods on non-internal types without a deprecation cycle

__Originally posted by @jvandort in https://github.com/gradle/gradle/pull/22913#discussion_r1036727703__

**Comment by Shoaib050041** [comment]
> We can't remove public methods on non-internal types without a deprecation cycle
> 
> __Originally posted by @jvandort in https://github.com/gradle/gradle/pull/22913#discussion_r1036727703__

**Comment by tresat** [comment]
FYI, the linked issue is now targeted for the next major version (Gradle 9.0).
